kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: mq2route 
  namespace: mq 
spec:
  host: tls2.chl.mq.ibm.com
  to:
    kind: Service
    name: mq2-ibm-mq 
  port:
    targetPort: 1414
  tls:
    termination: passthrough
